import { Metadata } from 'next';
import React from 'react'
import AllPostsPage from '../_components/AllPostsPage/AllPostsPage';

export const metadata: Metadata = {
  title: "Social Media App",
  description: "Social media app generated by create next app",
};
export default function page() {
  return <>
  <AllPostsPage/>
  </>
}
